In [1]:
import pandas as pd

df = pd.DataFrame({'학번': ['2301', '2302', '2303', '2304', '2305', '2306'],
                   '성명': ['홍길동', '유관순', '이순신', '이성계', '안중근', '홍범도'],
                   '나이': [27, 19, 35, 34, 22, None],
                   '영어': [70, 85, 75, None, 89, 57],
                   '수학': [80, 80, 90, 80, None, 88]})
print('+++++데이터프레임 출력(새로운 인덱스 열 추가)+++++')
print(df)

print('*****데이터프레임 인덱스 열="학번"으로 지정*****')
dfnew = df.set_index('학번')
print(dfnew)

student1 = {'학번': '2301', '성명': '홍길동', '나이': 27, '영어': 70, '수학': 80}
student2 = {'학번': '2302', '성명': '유관순', '나이': 19, '영어': 85, '수학': 80}
student3 = {'학번': '2303', '성명': '이순신', '나이': 35, '영어': 75, '수학': 90}
student4 = {'학번': '2304', '성명': '이성계', '나이': 34, '영어': None, '수학': 80}
student5 = {'학번': '2305', '성명': '안중근', '나이': 22, '영어': 89, '수학': None}
student6 = {'학번': '2306', '성명': '홍범도', '나이': None, '영어': 57, '수학': 88}

print('@@@@@딕셔너리를 데이터프레임으로 병합하기(새로운 인덱스 열 추가)@@@@@')
student = pd.DataFrame([student1, student2, student3, student4, student5, student6])
print(student)

print('!!!!!딕셔너리를 데이터프레임으로 병합하기(인덱스="학번"으로 지정!!!!!')
student = student.set_index('학번')
print(student)

+++++데이터프레임 출력(새로운 인덱스 열 추가)+++++
     학번   성명    나이    영어    수학
0  2301  홍길동  27.0  70.0  80.0
1  2302  유관순  19.0  85.0  80.0
2  2303  이순신  35.0  75.0  90.0
3  2304  이성계  34.0   NaN  80.0
4  2305  안중근  22.0  89.0   NaN
5  2306  홍범도   NaN  57.0  88.0
*****데이터프레임 인덱스 열="학번"으로 지정*****
       성명    나이    영어    수학
학번
2301  홍길동  27.0  70.0  80.0
2302  유관순  19.0  85.0  80.0
2303  이순신  35.0  75.0  90.0
2304  이성계  34.0   NaN  80.0
2305  안중근  22.0  89.0   NaN
2306  홍범도   NaN  57.0  88.0
@@@@@딕셔너리를 데이터프레임으로 병합하기(새로운 인덱스 열 추가)@@@@@
     학번   성명    나이    영어    수학
0  2301  홍길동  27.0  70.0  80.0
1  2302  유관순  19.0  85.0  80.0
2  2303  이순신  35.0  75.0  90.0
3  2304  이성계  34.0   NaN  80.0
4  2305  안중근  22.0  89.0   NaN
5  2306  홍범도   NaN  57.0  88.0
!!!!!딕셔너리를 데이터프레임으로 병합하기(인덱스="학번"으로 지정!!!!!
       성명    나이    영어    수학
학번
2301  홍길동  27.0  70.0  80.0
2302  유관순  19.0  85.0  80.0
2303  이순신  35.0  75.0  90.0
2304  이성계  34.0   NaN  80.0
2305  안중근  22.0  89.0   NaN
2306  홍범도   NaN  57.0  88.0

In [2]:
from google.colab import files
uploaded = files.upload()
import pandas as pd
df = pd.read_csv('./data.csv', encoding='euc-kr')
df.head()

FileNotFoundError: [Errno 2] No such file or directory: './data.csv'

In [ ]:
from google.colab import files
uploaded = files.upload()
import pandas as pd
df = pd.read_csv('./data.csv', encoding='euc-kr')
df.head()

In [ ]:
from google.colab import files
uploaded = files.upload()
import pandas as pd
df = pd.read_excel('./glass.xlsx')
df.head()

In [ ]:
from google.colab import files
uploaded = files.upload()
import pandas as pd
df = pd.read_table('./grade.txt', sep=',')
df.head()

In [ ]:
import google.colab.files as ftest
uploaded = ftest.upload()
import pandas as pd
df = pd.read_table('./grade.txt', sep=',')
df.head()

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/work/jeju.csv', encoding='euc-kr', index_col=0)
print(df.head())
print(df.info())

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/work/data.csv', encoding='euc-kr', index_col=0)
print(df.info())

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/work/data.csv', encoding='euc-kr', index_col=0)
print(df.head())
print(df.head(1))
print(df.tail(1))
display(df.head(2))

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/work/data.csv', encoding='euc-kr', index_col=0)
print('df.shape 수행 결과(행, 열): ', end=''); print(df.shape)
print('len(df) 수행 결과(행) ', end=''), print(len(df))
print('len(df.columns) 수행 결과(열): ', end=''); print(len(df.columns))
print('df.shape[0]의 수행 결과(행): ', end=''); print(df.shape[0])
print('df shape[1]의 수행 결과(열): ', end=''); print(df.shape[1])

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/work/data.csv', encoding='euc-kr', index_col=0)

print('data의 컬럼(속성)의 이름'); print(df.columns)
print('컬럼의 개수: ', end=''); print(len(df.columns))
print('data의 인덱스 열 이름: ', end=''); print(df.index.name)

print('인덱스 값'); print(df.index)
print('첫번째 인덱스 값: ', end=''); print(df.index[0])
print('인덱스 길이(행의 개수): ', end=''); print(len(df.index))

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/work/data.csv', encoding='euc-kr', index_col=0)

print('df의 데이터 자료 구조: ', end=''); print(type(df))
print(df.dtypes)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
import numpy as np

df = pd.read_csv('/content/drive/MyDrive/work/data.csv', encoding='euc-kr', index_col=0)

df['sum'] = df['쇼핑1월'] + df['쇼핑2월'] + df['쇼핑3월']
df['avg'] = df[['쇼핑1월', '쇼핑2월', '쇼핑3월']].apply(np.mean, axis=1)
df.rename(columns={'성별': 'Gender'}, inplace=True)
print(df.head())

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
import numpy as np
df = pd.read_csv('/content/drive/MyDrive/work/data.csv', encoding='euc-kr', index_col=0)
print('"성별"의 데이터 유형: ', end=''); print(df.dtypes['성별'])
df['gender'] = df['성별'].astype('category')
print('"gender"의 데이터 유형: ', end=''); print(df.dtypes['gender'])
df['gendernum'] = df['gender'].map({'남자': 1, '여자': 0})
df['gendernum'] = df['gendernum'].astype('int')
print('"gendernum"의 데이터 유형: ', end=''); print(df.dtypes['gendernum'])
print('전체 행의 개수(남성+여성)의 합계(명): ', end=''); print(df['gendernum'].count())
print('남성의 개수(명): ', end=''); print(df['gendernum'].sum())
print('여성의 개수(명)/len() 이용: ' , end=''); print(len(df.loc[df['gendernum'] == 0]))
print('여성의 개수(명)/shape[0] 이용: ', end=''); print(df.loc[df['gendernum']==0].shape[0])

ratio_male = df['gendernum'].sum() / df.shape[0]
print('남성의 비율(%): ', end=''); print(ratio_male*100)
ratio_female = len(df.loc[df['gendernum'] == 0]) / df.shape[0]
print('여성의 비율(%): ', end=''); print(ratio_female*100)

print('남성의 비율(%)/count(): ', end=''); print(100*df[df['gendernum']==1]['gendernum'].count() / df.shape[0])
print('여성의 비율(%)/count(): ', end=''); print(100*df[df['gendernum']==0]['gendernum'].count() / df.shape[0])

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
import numpy as np
data = pd.read_csv('/content/drive/MyDrive/work/data.csv', encoding='euc-kr', index_col=0)
print('## 스타필드 고객 데이터 ##')
print(data.head(2))
print('데이터 (행, 열)의 개수: ', end=''); print(data.shape)

print('@@ 남성 고객 데이터 @@')
datamale = data[data['성별'] == '남자']
print(datamale.head())
print('남성 데이터 (행,열)의 개수: ', end=''); print(datamale.shape)

print('%% 여성 고객 데이터 %%')
datafemale = data[data['성별'] == '여자']
print('여성 데이터 (행,열)의 개수: ', end=''); print(datafemale.shape)

print('&& 여성 고객의 이용만족도 &&')
df = datafemale[['이용만족도', '성별', '쇼핑액', '소득']]
print(df.head())

In [3]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
import numpy as np
data = pd.read_csv('/content/drive/MyDrive/work/data.csv', encoding='euc-kr', index_col=0)

print('@@ .query() 메소드 이용')
df1 = data.query('성별 == "남자"')
print(df1.head(2))
print('남성 고객의 수(행, 열)', end=''); print(df1.shape)

print('%% [조건문] 이용')
df2 = data[data.성별 == '여자']
print(df2.head(2))
print('여성 고객의 수(행, 열)', end=''); print(df2.shape)

print('|| .loc 인덱싱 이용')
df3 = data.loc[(data.성별 == '여자') & (data.쿠폰사용회수 >= 6)]
print(df3.head(2))
print('여성 고객들 중 쿠폰사용횟수가 6회 이상인 경우(행, 열): ', end=''); print(df3.shape)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
@@ .query() 메소드 이용
        성별     연령대   직업 주거지역    쇼핑액  이용만족도  쇼핑1월  쇼핑2월  쇼핑3월  쿠폰사용회수 쿠폰선호도  \
고객번호
190105  남자  45-49세  회사원  소도시  195.6      4  76.8  64.8  54.0       3     예
190106  남자  25-29세  공무원  소도시  116.4      7  44.4  32.4  39.6       6   아니오

        품질  가격  서비스  배송  쇼핑만족도    소득
고객번호
190105   7   7    1   4      4  4300
190106   7   4    7   7      7  7500
남성 고객의 수(행, 열)(55, 17)
%% [조건문] 이용
        성별     연령대   직업 주거지역    쇼핑액  이용만족도  쇼핑1월  쇼핑2월  쇼핑3월  쿠폰사용회수 쿠폰선호도  \
고객번호
190111  여자  50세 이상  공무원  중도시  207.6      4  64.8  88.8  54.0       4     예
190114  여자  45-49세  회사원  중도시  156.0      4  51.6  51.6  52.8       0     예

        품질  가격  서비스  배송  쇼핑만족도    소득
고객번호
190111   7   7    1   4      5  5700
190114   1   4    1   7      1  5700
여성 고객의 수(행, 열)(35, 17)
|| .loc 인덱싱 이용
        성별     연령대   직업 주거지역    쇼핑액  이용만족도  쇼핑1월  쇼핑2월  쇼핑3월  쿠폰사용회수 쿠폰선호도  \
고객번호
190140  여자  45-49세  전문직  대도시  210.0      7  90.0  67.2  52.8       6   아니오
190153  여자  40-44세  회사원  대도시  181.2      7  63.6  64.8  52.8       6     예

        품질  가격  서비스  배송  쇼핑만족도    소득
고객번호
190140   7   6    7   4      7  8200
190153   7   7    7   4      7  4700
여성 고객들 중 쿠폰사용횟수가 6회 이상인 경우(행, 열): (11, 17)

In [4]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
import numpy as np
data = pd.read_csv('/content/drive/MyDrive/work/data.csv', encoding='euc-kr', index_col=0)

df1 = data[['성별', '직업']]
print(df1.head(2))
df2 = data[['쇼핑액', '이용만족도']]
print(df2.head(2))

print('%% 데이터프레임 가로 병합(수직적 결합)')
dfconcat1 = pd.concat([df1, df2], axis=1)
print(dfconcat1.head())

df3 = data.loc[data.성별 == '남자']
print('남성 데이터: (행, 열): ', end=''); print(df3.shape)
df4 = data.loc[data.성별 == '여자']
print('여성 데이터: (행, 열): ', end=''); print(df4.shape)

print('%% 데이터프레임 세로 병합(수평적 결합)')
dfconcat2 = pd.concat([df3, df4], axis=0)
print(dfconcat2.head(2))
print(dfconcat2.shape)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
        성별   직업
고객번호
190105  남자  회사원
190106  남자  공무원
          쇼핑액  이용만족도
고객번호
190105  195.6      4
190106  116.4      7
%% 데이터프레임 가로 병합(수직적 결합)
        성별   직업    쇼핑액  이용만족도
고객번호
190105  남자  회사원  195.6      4
190106  남자  공무원  116.4      7
190107  남자  자영업  183.6      4
190108  남자  농어업  168.0      4
190109  남자  공무원  169.2      4
남성 데이터: (행, 열): (55, 17)
여성 데이터: (행, 열): (35, 17)
%% 데이터프레임 세로 병합(수평적 결합)
        성별     연령대   직업 주거지역    쇼핑액  이용만족도  쇼핑1월  쇼핑2월  쇼핑3월  쿠폰사용회수 쿠폰선호도  \
고객번호
190105  남자  45-49세  회사원  소도시  195.6      4  76.8  64.8  54.0       3     예
190106  남자  25-29세  공무원  소도시  116.4      7  44.4  32.4  39.6       6   아니오

        품질  가격  서비스  배송  쇼핑만족도    소득
고객번호
190105   7   7    1   4      4  4300
190106   7   4    7   7      7  7500
(90, 17)

In [5]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
import numpy as np
data = pd.read_csv('/content/drive/MyDrive/work/data.csv', encoding='euc-kr', index_col=0)

df = data[['성별', '직업', '쇼핑액', '이용만족도', '쿠폰사용회수']]
print(df.head(2))

print('## 쇼핑액 오름차순 정렬 ##')
df1 = df.sort_values(['쇼핑액'], ascending=True)
print(df1.head(3))

print('## 쇼핑액 내림차순 정렬 ##')
df2 = df.sort_values(by=['쇼핑액'], ascending=False)
print(df2.head(3))

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
        성별   직업    쇼핑액  이용만족도  쿠폰사용회수
고객번호
190105  남자  회사원  195.6      4       3
190106  남자  공무원  116.4      7       6
## 쇼핑액 오름차순 정렬 ##
        성별   직업   쇼핑액  이용만족도  쿠폰사용회수
고객번호
190156  여자  전문직  80.4      3       3
190170  남자  공무원  81.6      6       5
190176  여자  전문직  96.0      5       4
## 쇼핑액 내림차순 정렬 ##
        성별   직업    쇼핑액  이용만족도  쿠폰사용회수
고객번호
190117  남자  회사원  244.8      7       6
190188  여자  자영업  238.8      4       3
190144  여자  전문직  237.6      1       0

In [6]:
print('## 이용만족도 내림차순, 쿠폰사용회수 오름차순 정렬 ##')
df3 = df.sort_values(['이용만족도', '쿠폰사용회수'], ascending=[False, True])
print(df3.head(10))

## 이용만족도 내림차순, 쿠폰사용회수 오름차순 정렬 ##
        성별   직업    쇼핑액  이용만족도  쿠폰사용회수
고객번호
190112  남자  자영업  201.6      7       3
190139  여자  회사원  160.8      7       3
190141  여자  회사원  176.4      7       3
190162  여자  회사원  112.8      7       3
190183  남자  회사원  193.2      7       3
190149  남자  자영업  168.0      7       4
190178  남자  자영업  146.4      7       5
190186  여자  회사원  216.0      7       5
190106  남자  공무원  116.4      7       6
190117  남자  회사원  244.8      7       6

In [7]:
print('## 이용만족도 내림차순, 쿠폰사용회수 오름차순 정렬 ##')
df4 = df.sort_values(['이용만족도', '쿠폰사용회수'], ascending=[True, False])
print(df4.head(10))

## 이용만족도 내림차순, 쿠폰사용회수 오름차순 정렬 ##
        성별   직업    쇼핑액  이용만족도  쿠폰사용회수
고객번호
190144  여자  전문직  237.6      1       0
190169  여자  자영업  147.6      2       2
190192  여자  회사원  216.0      2       1
190113  남자  농어업  111.6      3       4
190184  남자  자영업  195.6      3       4
190122  남자  자영업  170.4      3       3
190156  여자  전문직   80.4      3       3
190161  남자  회사원  160.8      4       6
190175  여자  회사원  184.8      4       6
190107  남자  자영업  183.6      4       5

In [10]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
import numpy as np
data = pd.read_csv('/content/drive/MyDrive/work/data.csv', encoding='euc-kr', index_col=0)

df = data[['쇼핑1월', '쇼핑2월', '쇼핑3월']].copy()

def customer(x):
  if x['쇼핑2월'] >= 50 and x['쇼핑3월'] >= 52:
    return '우수고객'
  else:
    return '일반고객'

df.loc[:, 'isvip'] = df.apply(customer, axis=1)
print(df.head())

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
        쇼핑1월  쇼핑2월  쇼핑3월 isvip
고객번호
190105  76.8  64.8  54.0  우수고객
190106  44.4  32.4  39.6  일반고객
190107  66.0  66.0  51.6  일반고객
190108  62.4  52.8  52.8  우수고객
190109  63.6  54.0  51.6  일반고객

In [11]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
import numpy as np
data = pd.read_csv('/content/drive/MyDrive/work/data.csv', encoding='euc-kr', index_col=0)

df = data[['쇼핑1월', '쇼핑2월', '쇼핑3월']]
df['sum'] = df.apply(np.sum, axis=1)
df['avg'] = df.apply(np.mean, axis=1)

def gap(x):
  return (x['쇼핑2월']+x['쇼핑3월'])/2
df['(2월, 3월) 평균'] = df.apply(gap, axis=1)
print(df.head())

print('$$$ 열별 합계 $$$')
print(df.apply(np.sum, axis=0))
print('!!! 열별 평균 !!!')
print(df.apply(np.mean))

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
        쇼핑1월  쇼핑2월  쇼핑3월    sum   avg  (2월, 3월) 평균
고객번호
190105  76.8  64.8  54.0  195.6  97.8         59.4
190106  44.4  32.4  39.6  116.4  58.2         36.0
190107  66.0  66.0  51.6  183.6  91.8         58.8
190108  62.4  52.8  52.8  168.0  84.0         52.8
190109  63.6  54.0  51.6  169.2  84.6         52.8
$$$ 열별 합계 $$$
쇼핑1월            5847.6
쇼핑2월            5500.8
쇼핑3월            4329.6
sum            15678.0
avg             7839.0
(2월, 3월) 평균     4915.2
dtype: float64
!!! 열별 평균 !!!
쇼핑1월            64.973333
쇼핑2월            61.120000
쇼핑3월            48.106667
sum            174.200000
avg             87.100000
(2월, 3월) 평균     54.613333
dtype: float64

<ipython-input-11-489a65b7bdc1>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sum'] = df.apply(np.sum, axis=1)
<ipython-input-11-489a65b7bdc1>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['avg'] = df.apply(np.mean, axis=1)
<ipython-input-11-489a65b7bdc1>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['(2월, 3월) 평균'] = df.apply(gap, axis=1)

In [14]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
air = pd.read_csv('/content/drive/MyDrive/work/airquality.csv', encoding='euc-kr', index_col=0)

print(air.head())
print(air.info())
print(air.describe())
print(air.shape)
print(air.dtypes)
print('!! 항목별 결측값의 개수 !!')
print(air.isnull().sum())
print(air.isnull().head())

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
   Ozone  Solar.R  Wind  Temp  Month  Day
1   41.0    190.0   7.4    67      5    1
2   36.0    118.0   8.0    72      5    2
3   12.0    149.0  12.6    74      5    3
4   18.0    313.0  11.5    62      5    4
5    NaN      NaN  14.3    56      5    5
<class 'pandas.core.frame.DataFrame'>
Index: 153 entries, 1 to 153
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Ozone    116 non-null    float64
 1   Solar.R  146 non-null    float64
 2   Wind     153 non-null    float64
 3   Temp     153 non-null    int64
 4   Month    153 non-null    int64
 5   Day      153 non-null    int64
dtypes: float64(3), int64(3)
memory usage: 8.4 KB
None
            Ozone     Solar.R        Wind        Temp       Month         Day
count  116.000000  146.000000  153.000000  153.000000  153.000000  153.000000
mean    42.129310  185.931507    9.957516   77.882353    6.993464   15.803922
std     32.987885   90.058422    3.523001    9.465270    1.416522    8.864520
min      1.000000    7.000000    1.700000   56.000000    5.000000    1.000000
25%     18.000000  115.750000    7.400000   72.000000    6.000000    8.000000
50%     31.500000  205.000000    9.700000   79.000000    7.000000   16.000000
75%     63.250000  258.750000   11.500000   85.000000    8.000000   23.000000
max    168.000000  334.000000   20.700000   97.000000    9.000000   31.000000
(153, 6)
Ozone      float64
Solar.R    float64
Wind       float64
Temp         int64
Month        int64
Day          int64
dtype: object
!! 항목별 결측값의 개수 !!
Ozone      37
Solar.R     7
Wind        0
Temp        0
Month       0
Day         0
dtype: int64
   Ozone  Solar.R   Wind   Temp  Month    Day
1  False    False  False  False  False  False
2  False    False  False  False  False  False
3  False    False  False  False  False  False
4  False    False  False  False  False  False
5   True     True  False  False  False  False

In [16]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
air = pd.read_csv('/content/drive/MyDrive/work/airquality.csv', encoding='euc-kr', index_col=0)

data = air.dropna()
print('$$ 결측값 확인')
print(data.isnull().sum())
print('결측값 제외 후 (행, 열):axis=0(결측값 포함 행 삭제) ', end=''); print(data.shape)

df1 = air.dropna(axis=1)
print(data.isnull().sum())
print('결측값 제외 후 (행, 열):axis=0(결측값 포함 열 삭제) ', end=''); print(df1.shape)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
$$ 결측값 확인
Ozone      0
Solar.R    0
Wind       0
Temp       0
Month      0
Day        0
dtype: int64
결측값 제외 후 (행, 열):axis=0(결측값 포함 행 삭제) (111, 6)
Ozone      0
Solar.R    0
Wind       0
Temp       0
Month      0
Day        0
dtype: int64
결측값 제외 후 (행, 열):axis=0(결측값 포함 열 삭제) (153, 4)

In [17]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
import numpy as np
air = pd.read_csv('/content/drive/MyDrive/work/airquality.csv', encoding='euc-kr', index_col=0)

median = air.dropna()['Ozone'].median()
avg = air.dropna()['Ozone'].mean()
print('결측값을 제외한 Ozone의 중앙값(median): ', end=''); print(median)
print('결측값을 제외한 Ozone의 평균(mean): ', end=''); print(avg)
print('Ozone 항목의 결측값 개수: ', end=''); print(air['Ozone'].isnull().sum())

print('------------------------------')
air['Ozone'].fillna(median, inplace=True)
print('결측값을 중앙값으로 대체한 후 Ozone의 중앙값(median): ', end=''); print(air['Ozone'].median())
print('결측값을 중앙값으로 대체한 후 Ozone의 평균(mean): ', end=''); print(air['Ozone'].mean())
print('Ozone 항목의 대체 후 결측값 개수: ', end=''); print(air['Ozone'].isnull().sum())

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
결측값을 제외한 Ozone의 중앙값(median): 31.0
결측값을 제외한 Ozone의 평균(mean): 42.0990990990991
Ozone 항목의 결측값 개수: 37
------------------------------
결측값을 중앙값으로 대체한 후 Ozone의 중앙값(median): 31.0
결측값을 중앙값으로 대체한 후 Ozone의 평균(mean): 39.43790849673203
Ozone 항목의 대체 후 결측값 개수: 0

In [18]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
import numpy as np
air = pd.read_csv('/content/drive/MyDrive/work/airquality.csv', encoding='euc-kr', index_col=0)

avg = air.dropna()['Solar.R'].mean()
print('결측값을 제외한 Solar.R의 평균(mean): ', end=''); print(avg)
print('Solar.R 항목의 결측값 개수: ', end=''); print(air['Solar.R'].isnull().sum())

print('------------------------------')
air['Solar.R'].fillna(avg, inplace=True)
print('결측값을 평균값으로 대체한 후 Solar.R의 평균(mean): ', end=''); print(air['Solar.R'].mean())
print('Solar.R 항목의 대체 후 결측값 개수: ', end=''); print(air['Solar.R'].isnull().sum())

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
결측값을 제외한 Solar.R의 평균(mean): 184.80180180180182
Solar.R 항목의 결측값 개수: 7
------------------------------
결측값을 평균값으로 대체한 후 Solar.R의 평균(mean): 185.87982099746807
Solar.R 항목의 대체 후 결측값 개수: 0

In [20]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
air = pd.read_csv('/content/drive/MyDrive/work/airquality.csv', encoding='euc-kr', index_col=0)

data = air.dropna()
q = data['Ozone'].quantile()
print('Ozone의 2사분위 수(하위 50%, 중앙값): ', end=''); print(q)
q1 = data['Ozone'].quantile(0.25)
print('Ozone의 1사분위 수(하위 25%): ', end=''); print(q1)
q2 = data['Ozone'].quantile(0.5)
print('Ozone의 2사분위 수(하위 50%, 중앙값): ', end=''); print(q2)
q3 = data['Ozone'].quantile(0.75)
print('Ozone의 3사분위 수(하위 75%): ', end=''); print(q3)
Iqr = q3 - q1
print('Ozone의 사분위 수 범위(하위 75% - 하위 25%): ', end=''); print(Iqr)

print('@@ Ozone의 기술통계량 요약 @@')
print(data['Ozone'].describe())
print('Ozone의 사분위 수 범위(하위 75% - 하위 25%)/describe()이용: ', end='')
print(data['Ozone'].describe()['75%'] - data['Ozone'].describe()['25%'])

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Ozone의 2사분위 수(하위 50%, 중앙값): 31.0
Ozone의 1사분위 수(하위 25%): 18.0
Ozone의 2사분위 수(하위 50%, 중앙값): 31.0
Ozone의 3사분위 수(하위 75%): 62.0
Ozone의 사분위 수 범위(하위 75% - 하위 25%): 44.0
@@ Ozone의 기술통계량 요약 @@
count    111.000000
mean      42.099099
std       33.275969
min        1.000000
25%       18.000000
50%       31.000000
75%       62.000000
max      168.000000
Name: Ozone, dtype: float64
Ozone의 사분위 수 범위(하위 75% - 하위 25%)/describe()이용: 44.0

In [21]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
air = pd.read_csv('/content/drive/MyDrive/work/airquality.csv', encoding='euc-kr', index_col=0)
data = air.dropna(subset=['Ozone'])
print(data.describe())
iqr = data['Ozone'].describe()['75%']  - data['Ozone'].describe()['25%']
r1 = data['Ozone'].mean() - 0.5*iqr
r2 = data['Ozone'].mean() + 0.5*iqr
print('평균-사분위수범위(하한 경계값): ', end=''); print(r1)
print('평균+사분위수범위(상한 경계값): ', end=''); print(r2)

cond = (data['Ozone'] <= r1) | (data['Ozone'] >= r2)

print('조건을 만족하는 행(Ozone 항목)의 개수: ', end=''); print(sum(cond))
print('조건을 만족하는 각 컬럼 값의 합')
print(data[cond].sum())

print('------------------------------')
print('조건을 만족하는 각 컬럼 값의 평균')
print(data[cond].mean())
print('조건을 만족하는 Solar.R의 평균: ', end=''); print(data[cond]['Solar.R'].mean())

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
            Ozone     Solar.R        Wind        Temp       Month         Day
count  116.000000  111.000000  116.000000  116.000000  116.000000  116.000000
mean    42.129310  184.801802    9.862069   77.870690    7.198276   15.534483
std     32.987885   91.152302    3.574856    9.485486    1.475715    8.750087
min      1.000000    7.000000    2.300000   57.000000    5.000000    1.000000
25%     18.000000  113.500000    7.400000   71.000000    6.000000    8.000000
50%     31.500000  207.000000    9.700000   79.000000    7.000000   16.000000
75%     63.250000  255.500000   11.500000   85.000000    8.250000   22.000000
max    168.000000  334.000000   20.700000   97.000000    9.000000   31.000000
평균-사분위수범위(하한 경계값): 19.504310344827587
평균+사분위수범위(상한 경계값): 64.75431034482759
조건을 만족하는 행(Ozone 항목)의 개수: 60
조건을 만족하는 각 컬럼 값의 합
Ozone      2895.0
Solar.R    9784.0
Wind        568.7
Temp       4691.0
Month       428.0
Day         931.0
dtype: float64
---------------
조건을 만족하는 각 컬럼 값의 평균
Ozone       48.250000
Solar.R    171.649123
Wind         9.478333
Temp        78.183333
Month        7.133333
Day         15.516667
dtype: float64
조건을 만족하는 Solar.R의 평균: 171.64912280701753

In [22]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

air = pd.read_csv('/content/drive/MyDrive/work/airquality.csv', index_col=0)
data = air.dropna()
print(data.describe())

print('@@ lambda 람다식 이용 @@')
scale = lambda x: (x-x.min(axis=0))/(x.max(axis=0)-x.min(axis=0))
data['Ozone'] = scale(data['Ozone'])
print(data.head())

print('--- sklearn 모듈(MinMaxScaler) 이용---')
df = air.dropna()
scaler = MinMaxScaler()
dfnew = scaler.fit_transform(df)
print(dfnew[:5])
df['Ozone_scaled'] = dfnew[:,0]
print(df.head())

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
            Ozone     Solar.R        Wind        Temp       Month         Day
count  111.000000  111.000000  111.000000  111.000000  111.000000  111.000000
mean    42.099099  184.801802    9.939640   77.792793    7.216216   15.945946
std     33.275969   91.152302    3.557713    9.529969    1.473434    8.707194
min      1.000000    7.000000    2.300000   57.000000    5.000000    1.000000
25%     18.000000  113.500000    7.400000   71.000000    6.000000    9.000000
50%     31.000000  207.000000    9.700000   79.000000    7.000000   16.000000
75%     62.000000  255.500000   11.500000   84.500000    9.000000   22.500000
max    168.000000  334.000000   20.700000   97.000000    9.000000   31.000000
@@ lambda 람다식 이용 @@
      Ozone  Solar.R  Wind  Temp  Month  Day
1  0.239521    190.0   7.4    67      5    1
2  0.209581    118.0   8.0    72      5    2
3  0.065868    149.0  12.6    74      5    3
4  0.101796    313.0  11.5    62      5    4
7  0.131737    299.0   8.6    65      5    7
--- sklearn 모듈(MinMaxScaler) 이용---
[[0.23952096 0.55963303 0.27717391 0.25       0.         0.        ]
 [0.20958084 0.33944954 0.30978261 0.375      0.         0.03333333]
 [0.06586826 0.43425076 0.55978261 0.425      0.         0.06666667]
 [0.10179641 0.93577982 0.5        0.125      0.         0.1       ]
 [0.13173653 0.89296636 0.3423913  0.2        0.         0.2       ]]
   Ozone  Solar.R  Wind  Temp  Month  Day  Ozone_scaled
1   41.0    190.0   7.4    67      5    1      0.239521
2   36.0    118.0   8.0    72      5    2      0.209581
3   12.0    149.0  12.6    74      5    3      0.065868
4   18.0    313.0  11.5    62      5    4      0.101796
7   23.0    299.0   8.6    65      5    7      0.131737

<ipython-input-22-392a3d02ecd8>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Ozone'] = scale(data['Ozone'])
<ipython-input-22-392a3d02ecd8>:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Ozone_scaled'] = dfnew[:,0]

In [24]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
from sklearn.preprocessing import StandardScaler

air = pd.read_csv('/content/drive/MyDrive/work/airquality.csv', index_col=0)
data = air.dropna()

print('## 람다식 이용 ##')
zscale = lambda x: (x-x.mean())/ x.std()
data['Ozone'] = zscale(data['Ozone'])
print(data.head())

print('%% sklearn 모듈 이용, StandardScaler() %%')
df = air.dropna()
zscaler = StandardScaler()
dfnew = zscaler.fit_transform(df)
print(dfnew[:5])
df['Ozone_zscaled'] = dfnew[:, 0]
print(df.head())
print('Z-score 변환 후 평균값: ', end=''); print(df['Ozone_zscaled'].mean())
print('Z-score 변환 후 표준편차: ', end=''); print(df['Ozone_zscaled'].std())

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
## 람다식 이용 ##
      Ozone  Solar.R  Wind  Temp  Month  Day
1 -0.033030    190.0   7.4    67      5    1
2 -0.183288    118.0   8.0    72      5    2
3 -0.904530    149.0  12.6    74      5    3
4 -0.724219    313.0  11.5    62      5    4
7 -0.573961    299.0   8.6    65      5    7
%% sklearn 모듈 이용, StandardScaler() %%
[[-0.03317961  0.05728624 -0.71707784 -1.13764691 -1.51093794 -1.72429003]
 [-0.18411965 -0.73618283 -0.54766534 -0.61060682 -1.51093794 -1.60892161]
 [-0.90863181 -0.39455031  0.75116384 -0.39979078 -1.51093794 -1.4935532 ]
 [-0.72750377  1.4127959   0.44057426 -1.66468701 -1.51093794 -1.37818479]
 [-0.57656373  1.25851025 -0.37825284 -1.34846295 -1.51093794 -1.03207956]]
   Ozone  Solar.R  Wind  Temp  Month  Day  Ozone_zscaled
1   41.0    190.0   7.4    67      5    1      -0.033180
2   36.0    118.0   8.0    72      5    2      -0.184120
3   12.0    149.0  12.6    74      5    3      -0.908632
4   18.0    313.0  11.5    62      5    4      -0.727504
7   23.0    299.0   8.6    65      5    7      -0.576564
Z-score 변환 후 평균값: -1.6003214769371626e-17
Z-score 변환 후 표준편차: 1.0045351706590016

<ipython-input-24-6bb04589f3c3>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Ozone'] = zscale(data['Ozone'])
<ipython-input-24-6bb04589f3c3>:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Ozone_zscaled'] = dfnew[:, 0]

In [26]:
import pandas as pd
data = pd.DataFrame({'학번': ['2301', '2302', '2303', '2304', '2305', '2306'],
                     '성명': ['홍길동', '유관순', '이순신', '이성계', '장유진', '임영미'],
                     '나이': [27, 19, 35, 34, 22, None],
                     '영어': [70, 85, 75, None, 89, 57],
                     '수학': [80, 80, 90, 80, None, 88]})
print('*****데이터프레임 인덱스 열="학번"으로 지정*****')
df = data.set_index('학번')
print(df)
print('index 이름: ', end=''); print(df.index)
print('columns 이름: ', end=''); print(df.columns)

print('^^^ 행 추출 ^^^')
print(df.loc['2302'])
print(df.iloc[1])

print('### 열 추출 ###')
print(df['나이'])
print(df.나이)

print('@@@ (행,열) 추출 @@@')
print(df.loc['2306']['수학'])
print(df.iloc[5][3])

*****데이터프레임 인덱스 열="학번"으로 지정*****
       성명    나이    영어    수학
학번
2301  홍길동  27.0  70.0  80.0
2302  유관순  19.0  85.0  80.0
2303  이순신  35.0  75.0  90.0
2304  이성계  34.0   NaN  80.0
2305  장유진  22.0  89.0   NaN
2306  임영미   NaN  57.0  88.0
index 이름: Index(['2301', '2302', '2303', '2304', '2305', '2306'], dtype='object', name='학번')
columns 이름: Index(['성명', '나이', '영어', '수학'], dtype='object')
^^^ 행 추출 ^^^
성명     유관순
나이    19.0
영어    85.0
수학    80.0
Name: 2302, dtype: object
성명     유관순
나이    19.0
영어    85.0
수학    80.0
Name: 2302, dtype: object
### 열 추출 ###
학번
2301    27.0
2302    19.0
2303    35.0
2304    34.0
2305    22.0
2306     NaN
Name: 나이, dtype: float64
학번
2301    27.0
2302    19.0
2303    35.0
2304    34.0
2305    22.0
2306     NaN
Name: 나이, dtype: float64
@@@ (행,열) 추출 @@@
88.0
88.0

In [29]:
import pandas as pd
data = pd.DataFrame({'학번': ['2301', '2302', '2303', '2304', '2305', '2306'],
                     '성명': ['홍길동', '유관순', '이순신', '이성계', '장유진', '임영미'],
                     '나이': [27, 19, 35, 34, 22, None],
                     '영어': [70, 85, 75, None, 89, 57],
                     '수학': [80, 80, 90, 80, None, 88]})
df = data.set_index('학번')

df1 = df[['성명', '나이']]
print(df1.head(2))
df2 = df[['영어', '수학']]
print(df2.head(2))
print('------ concat() 메소드 이용 ------')
dfconcat = pd.concat([df1, df2], axis=1)
print(dfconcat)

print('### merge() 메소드 이용 ###')
dfmerge = pd.merge(df1, df2, on='학번')
print(dfmerge)

print('&& isin() 함수 사용 예 &&')
result = dfmerge[dfmerge['성명'].isin(['장유진'])]
print(result)
result1 = dfmerge[dfmerge['성명'].isin(['장유진', '임영미'])]
print(result1)

       성명    나이
학번
2301  홍길동  27.0
2302  유관순  19.0
        영어    수학
학번
2301  70.0  80.0
2302  85.0  80.0
------ concat() 메소드 이용 ------
       성명    나이    영어    수학
학번
2301  홍길동  27.0  70.0  80.0
2302  유관순  19.0  85.0  80.0
2303  이순신  35.0  75.0  90.0
2304  이성계  34.0   NaN  80.0
2305  장유진  22.0  89.0   NaN
2306  임영미   NaN  57.0  88.0
### merge() 메소드 이용 ###
       성명    나이    영어    수학
학번
2301  홍길동  27.0  70.0  80.0
2302  유관순  19.0  85.0  80.0
2303  이순신  35.0  75.0  90.0
2304  이성계  34.0   NaN  80.0
2305  장유진  22.0  89.0   NaN
2306  임영미   NaN  57.0  88.0
&& isin() 함수 사용 예 &&
       성명    나이    영어  수학
학번
2305  장유진  22.0  89.0 NaN
       성명    나이    영어    수학
학번
2305  장유진  22.0  89.0   NaN
2306  임영미   NaN  57.0  88.0

In [31]:
import pandas as pd
data = pd.DataFrame({'학번': ['2301', '2302', '2303'],
                     '성명': ['홍길동', '장유진', '임영미'],
                     '나이': [27, 19, 35],
                     '영어': [70,85, 75],
                     '수학': [80, 80, 90]})
df = data.set_index('학번')
print(df.iterrows())
print('@@@ 행(row) 방향으로 순회하기(행 인덱스 이름 사용), iterrows() 메소드 이용 @@@')

sumeng = 0
for index, row in df.iterrows():
  sumeng += row['영어']
  print(index, row['성명'], row['영어'])
print('영어점수 합계: ', end=''); print(sumeng)
print('!!! 행(row) 방향으로 순회하기(행 위치번호 사용), df.shape[0]:행의 개수) !!!')
summath = 0
for i in range(0, df.shape[0]):
  index = df.index[i]
  summath += df.iloc[1][3]
  print(index, df.loc[index]['성명'], df.loc[index]['수학'])
print('수학점수 합계: ', end=''); print(summath)
print('%%% 열(column) 방향으로 순회하기(열 이름 사용), df.columns: 열이름 %%%')
sumhap = 0
for col in df.columns:
  if col == '영어' or col == '수학':
    sumhap += df[col]
print('학번별 (영어+수학) 점수 합계: '); print(sumhap)
print('^^^ 열(column) 방향으로 순회하기(열 위치번호 사용), df.shape[1]: 열의 개수 ^^^')
sumhap = 0
for i in range(0, df.shape[1]):
  col = df.columns[i]
  if col == '영어' or col == '수학':
    sumhap += df.iloc[:, i]
print('학번별 (영어+수학) 점수 합계: '); print(sumhap)

<generator object DataFrame.iterrows at 0x7ca95e27ace0>
@@@ 행(row) 방향으로 순회하기(행 인덱스 이름 사용), iterrows() 메소드 이용 @@@
2301 홍길동 70
2302 장유진 85
2303 임영미 75
영어점수 합계: 230
!!! 행(row) 방향으로 순회하기(행 위치번호 사용), df.shape[0]:행의 개수) !!!
2301 홍길동 80
2302 장유진 80
2303 임영미 90
수학점수 합계: 240
%%% 열(column) 방향으로 순회하기(열 이름 사용), df.columns: 열이름 %%%
학번별 (영어+수학) 점수 합계:
학번
2301    150
2302    165
2303    165
Name: 영어, dtype: int64
^^^ 열(column) 방향으로 순회하기(열 위치번호 사용), df.shape[1]: 열의 개수 ^^^
학번별 (영어+수학) 점수 합계:
학번
2301    150
2302    165
2303    165
Name: 영어, dtype: int64

In [33]:
import pandas as pd
data = pd.DataFrame({'학번': ['2301', '2302', '2303'],
                     '성명': ['홍길동', '장유진', '임영미'],
                     '나이': [27, 19, 35],
                     '영어': [70, 85, 75],
                     '수학': [80, 80, 90]})
df = data.set_index('학번')
print('### itertuples() 메소드 이용 데이터프레임 참조, 행(tuple)별 순회 ###')
for item in df.itertuples():
  for i in range(len(item)):
    print(item[i])
  print('--- next ---')

print('$$$ 특정 열 순회, 열이름 참조 $$$')
for item in df['성명']:
  print(item)
print('***')

print('$$$ 특정 행 순회, 행번호 참조 $$$')
for item in df.iloc[1]:
  print(item)

print('$$$ 특정 열 순회, 행번호 참조 $$$')
for item1, item2 in zip(df['성명'], df['나이']):
  print(item1, item2)

print('$$$ 특정 열 순회, zip(열이름, 행번호) 참조 $$$')
for item1, item2 in zip(df['성명'], df.iloc[2]):
  print(item1, item2)

### itertuples() 메소드 이용 데이터프레임 참조, 행(tuple)별 순회 ###
2301
홍길동
27
70
80
--- next ---
2302
장유진
19
85
80
--- next ---
2303
임영미
35
75
90
--- next ---
$$$ 특정 열 순회, 열이름 참조 $$$
홍길동
장유진
임영미
***
$$$ 특정 행 순회, 행번호 참조 $$$
장유진
19
85
80
$$$ 특정 열 순회, 행번호 참조 $$$
홍길동 27
장유진 19
임영미 35
$$$ 특정 열 순회, zip(열이름, 행번호) 참조 $$$
홍길동 임영미
장유진 35
임영미 75

In [34]:
import pandas as pd
data = pd.DataFrame({'학번': ['2301', '2302', '2303'],
                     '성명': ['홍길동', '장유진', '임영미'],
                     '나이': [27, 19, 35],
                     '영어': [70, 85, 75],
                     '수학': [80, 80, 90]})
df = data.set_index('학번')
dfseries1 = df['성명']
print(dfseries1)
print(type(dfseries1))
print(dfseries1.index)
print(dfseries1['2302'])
print(dfseries1[2])

print('--------------------')
dfseries2 = df['수학']
dftotal = pd.concat([dfseries1, dfseries2], axis=1)
print(dftotal)
print(type(dftotal))

학번
2301    홍길동
2302    장유진
2303    임영미
Name: 성명, dtype: object
<class 'pandas.core.series.Series'>
Index(['2301', '2302', '2303'], dtype='object', name='학번')
장유진
임영미
--------------------
       성명  수학
학번
2301  홍길동  80
2302  장유진  80
2303  임영미  90
<class 'pandas.core.frame.DataFrame'>

In [35]:
import pandas as pd
data = pd.DataFrame({'학번': ['2301', '2302', '2303'],
                     '성명': ['홍길동', '장유진', '임영미'],
                     '나이': [27, 19, 35],
                     '영어': [70, 85, 75],
                     '수학': [80, 80, 90]})
df = data.set_index('학번')

dfrow1 = df.loc['2302']
print(dfrow1)
print(type(dfrow1))
print(dfrow1.index)
print(dfrow1['나이'])
print(dfrow1[3])

print('&&&&&&&&&&&&&&&&&&&&')
dfrow2 = df.loc['2303']
dfrowtotal = pd.concat([dfrow1, dfrow2], axis=1).transpose()
dfrowtotal.index.name = '학번'
print(dfrowtotal)
print(dfrowtotal.index)
print(type(dfrowtotal))

성명    장유진
나이     19
영어     85
수학     80
Name: 2302, dtype: object
<class 'pandas.core.series.Series'>
Index(['성명', '나이', '영어', '수학'], dtype='object')
19
80
&&&&&&&&&&&&&&&&&&&&
       성명  나이  영어  수학
학번
2302  장유진  19  85  80
2303  임영미  35  75  90
Index(['2302', '2303'], dtype='object', name='학번')
<class 'pandas.core.frame.DataFrame'>

In [39]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
data = pd.read_csv('/content/drive/MyDrive/work/data.csv', encoding='euc-kr', index_col=0)

print('%%% 성별에 따른 항목별 평균 %%%')
# print(data.groupby('성별').mean())

print('----------성별에 따른 소득의 평균----------')
print(data.groupby('성별')['소득'].mean())

print('----------성별에 따른 소득의 분산----------')
print(data.groupby('성별')['소득'].var())

print('----------성별에 따른 소득의 표준편차----------')
print(data.groupby('성별')['소득'].std())

print('----------성별에 따른 소득의 (평균, 표준편차)/agg() 이용----------')
print(data.groupby('성별')['소득'].agg(['mean', 'std']))

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
%%% 성별에 따른 항목별 평균 %%%
----------성별에 따른 소득의 평균----------
성별
남자    5159.090909
여자    5270.000000
Name: 소득, dtype: float64
----------성별에 따른 소득의 분산----------
성별
남자    3.932231e+06
여자    2.877382e+06
Name: 소득, dtype: float64
----------성별에 따른 소득의 표준편차----------
성별
남자    1982.985285
여자    1696.284868
Name: 소득, dtype: float64
----------성별에 따른 소득의 (평균, 표준편차)/agg() 이용----------
           mean          std
성별
남자  5159.090909  1982.985285
여자  5270.000000  1696.284868

In [40]:
cd /content/drive/MyDrive/Github/BigDataCert

/content/drive/MyDrive/Github/BigDataCert